### ISSUE TITLE
Feature: Time planning and tracking

### ISSUE THREAD

**Issue by jgaa** [jgaa/next-app#54]
Requirements

- [ ] We need some kind of category that can be assigned to a node and overridden in an action.
- [ ] We need a way to define how much time we plan to spend on the various categories in a period of time. The simplest is to use months or weeks. 
- [ ] Graphical presentation about the current utilization of time relative to the goal
- [ ] Graphical presentation about past utilizations relative to the goal.

May be the best is to allow planning over at timeline, with weekly goals. We could also allow weekly *and* monthly goals, and visualize if they are misaligned. Then we track the time spent via work sessions/Actions.
